const BACKEND_CONSOLE_I18N = {
  zh: {
    productKicker: "地图社区平台",
    productTitle: "Scenario Forge 社区与后台",
    productCopy: "玩家看到社区、存档和评论；管理员看到审核队列、用户状态、权限和社区动态。",
    openEditor: "打开编辑器",
    communityView: "公开社区",
    accountView: "用户中心",
    adminView: "管理员后台",
    login: "登录",
    register: "注册",
    logout: "登出",
    communityKicker: "玩家视角",
    communityTitle: "社区帖子流",
    refreshCommunity: "刷新社区",
    seedDemo: "生成样例帖子",
    accountGateTitle: "登录后查看用户中心",
    accountGateCopy: "用户中心只展示当前用户自己的存档、发布状态和导出操作。",
    accountKicker: "用户视角",
    myLibrary: "我的存档库",
    createSample: "创建示例存档",
    newPost: "发布前草稿",
    title: "标题",
    description: "描述",
    imageUrl: "封面图片 URL",
    saveDraft: "保存为私有草稿",
    adminGateTitle: "管理员权限后进入后台",
    adminGateCopy: "后台入口只给 admin 或 moderator 显示，所有管理动作都经过后端权限校验。",
    metricUsers: "用户",
    metricSaves: "帖子",
    metricPublic: "公开",
    metricReports: "待审举报",
    metricComments: "评论",
    metricBanned: "封禁",
    refreshAdmin: "刷新后台",
    activityTab: "动态",
    contentTab: "内容",
    commentsTab: "评论",
    usersTab: "用户",
    reportsTab: "举报",
    activityTitle: "社区动态",
    contentTitle: "内容与图片管理",
    commentsTitle: "评论管理",
    usersTitle: "用户与权限",
    reportsTitle: "举报审核",
    username: "用户名",
    password: "密码",
    displayName: "显示名称",
    downloadJson: "下载 JSON",
    languageButton: "English",
    loggedOut: "未登录",
    noCommunity: "还没有社区帖子。管理员可先生成样例帖子。",
    noSaves: "你还没有存档。",
    noAdmin: "后台数据暂不可用。",
    noItems: "暂无内容。",
    detail: "详情",
    publish: "发布",
    export: "导出",
    download: "下载",
    comment: "评论",
    report: "举报",
    save: "存档",
    private: "私有",
    public: "公开",
    active: "正常",
    banned: "封禁",
    visible: "可见",
    hidden: "已隐藏",
    open: "待处理",
    reviewed: "已审核",
    member: "成员",
    moderator: "版主",
    admin: "管理员",
    commentsOpen: "评论开放",
    commentsClosed: "评论关闭",
    closeComments: "关闭评论",
    openComments: "开放评论",
    hideComment: "隐藏评论",
    reviewReport: "标记已审核",
    makePrivate: "设为私有",
    makePublic: "设为公开",
    clearImage: "清除图片",
    banUser: "封禁用户",
    unbanUser: "解除封禁",
    promoteModerator: "设为版主",
    promoteAdmin: "设为管理员",
    demoteMember: "设为成员",
    loginRequired: "请先登录。",
    adminRequired: "需要管理员或版主权限。",
    saved: "已保存。",
    registered: "已注册并登录。",
    loggedIn: "已登录。",
    loggedOutToast: "已登出。",
    demoSeeded: "样例帖子已生成。",
    actionDone: "操作完成。",
    backendUnavailable: "请从本地 dev server 打开这个页面。",
    unknown: "未知",
    by: "作者",
    comments: "评论",
    reports: "举报",
    imageManaged: "图片已更新。",
  },
  en: {
    productKicker: "Map Community Platform",
    productTitle: "Scenario Forge Community and Admin",
    productCopy: "Players see community posts, saves, and comments; admins see review queues, users, roles, and activity.",
    openEditor: "Open editor",
    communityView: "Public community",
    accountView: "User center",
    adminView: "Admin backend",
    login: "Login",
    register: "Register",
    logout: "Logout",
    communityKicker: "Player view",
    communityTitle: "Community feed",
    refreshCommunity: "Refresh community",
    seedDemo: "Create sample posts",
    accountGateTitle: "Login to view user center",
    accountGateCopy: "The user center only shows your own saves, publish state, and exports.",
    accountKicker: "User view",
    myLibrary: "My save library",
    createSample: "Create sample save",
    newPost: "Draft before publishing",
    title: "Title",
    description: "Description",
    imageUrl: "Cover image URL",
    saveDraft: "Save private draft",
    adminGateTitle: "Admin permission required",
    adminGateCopy: "The backend appears only for admins or moderators; every action is checked by the backend.",
    metricUsers: "Users",
    metricSaves: "Posts",
    metricPublic: "Public",
    metricReports: "Open reports",
    metricComments: "Comments",
    metricBanned: "Banned",
    refreshAdmin: "Refresh admin",
    activityTab: "Activity",
    contentTab: "Content",
    commentsTab: "Comments",
    usersTab: "Users",
    reportsTab: "Reports",
    activityTitle: "Community activity",
    contentTitle: "Content and image management",
    commentsTitle: "Comment management",
    usersTitle: "Users and roles",
    reportsTitle: "Report review",
    username: "Username",
    password: "Password",
    displayName: "Display name",
    downloadJson: "Download JSON",
    languageButton: "中文",
    loggedOut: "Logged out",
    noCommunity: "No community posts yet. Admins can create sample posts.",
    noSaves: "No saves yet.",
    noAdmin: "Admin data unavailable.",
    noItems: "No items.",
    detail: "Detail",
    publish: "Publish",
    export: "Export",
    download: "Download",
    comment: "Comment",
    report: "Report",
    save: "Save",
    private: "private",
    public: "public",
    active: "active",
    banned: "banned",
    visible: "visible",
    hidden: "hidden",
    open: "open",
    reviewed: "reviewed",
    member: "member",
    moderator: "moderator",
    admin: "admin",
    commentsOpen: "Comments open",
    commentsClosed: "Comments closed",
    closeComments: "Close comments",
    openComments: "Open comments",
    hideComment: "Hide comment",
    reviewReport: "Mark reviewed",
    makePrivate: "Make private",
    makePublic: "Make public",
    clearImage: "Clear image",
    banUser: "Ban user",
    unbanUser: "Unban user",
    promoteModerator: "Make moderator",
    promoteAdmin: "Make admin",
    demoteMember: "Make member",
    loginRequired: "Login first.",
    adminRequired: "Admin or moderator permission required.",
    saved: "Saved.",
    registered: "Registered and logged in.",
    loggedIn: "Logged in.",
    loggedOutToast: "Logged out.",
    demoSeeded: "Sample posts created.",
    actionDone: "Done.",
    backendUnavailable: "Open this page from the local dev server.",
    unknown: "Unknown",
    by: "by",
    comments: "comments",
    reports: "reports",
    imageManaged: "Image updated.",
  },
};

function normalizeBackendConsoleLocale(locale = "zh") {
  return Object.prototype.hasOwnProperty.call(BACKEND_CONSOLE_I18N, locale) ? locale : "zh";
}

function translateBackendConsole(locale, key, vars = {}) {
  const resolvedLocale = normalizeBackendConsoleLocale(locale);
  const template = BACKEND_CONSOLE_I18N[resolvedLocale]?.[key] || BACKEND_CONSOLE_I18N.zh[key] || key;
  return Object.entries(vars).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), template);
}

function getBackendConsoleDocumentLang(locale) {
  return normalizeBackendConsoleLocale(locale) === "zh" ? "zh-Hans" : "en";
}

function getBackendConsoleTitle(locale) {
  return translateBackendConsole(locale, "productTitle");
}

function getBackendConsoleMessageKeys(locale) {
  const resolvedLocale = normalizeBackendConsoleLocale(locale);
  return Object.keys(BACKEND_CONSOLE_I18N[resolvedLocale]);
}

function sampleProjectPayload(label = "console") {
  return {
    schemaVersion: 21,
    paintMode: "visual",
    mapSemanticMode: "scenario",
    activePaletteId: label,
    layerVisibility: { political: true, transport: true },
    timestamp: new Date().toISOString(),
  };
}

function formatDate(value) {
  if (!value) return "";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString();
}

function escapeHtml(value) {
  return String(value ?? "").replace(/[&<>"']/g, (char) => (
    { "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[char]
  ));
}

function escapeAttr(value) {
  return escapeHtml(value).replace(/`/g, "&#96;");
}

export {
  escapeAttr,
  escapeHtml,
  formatDate,
  getBackendConsoleDocumentLang,
  getBackendConsoleMessageKeys,
  getBackendConsoleTitle,
  normalizeBackendConsoleLocale,
  sampleProjectPayload,
  translateBackendConsole,
};
