export const VERIFICATION_RESOURCE_LOCKS = Object.freeze([
  "browser-dev-server",
  "perf-dev-server",
  "playwright-browser",
  "dist",
  ".runtime-output",
  "scenario-data",
  "heavy-geo",
  "checkpoint-builder",
  "system-power-scheme",
]);

export const VERIFICATION_EXECUTION_OWNERS = Object.freeze([
  "child-safe",
  "main-thread",
  "ci-only",
]);

export const VERIFICATION_COSTS = Object.freeze([
  "fast",
  "contract",
  "heavy",
]);

export const VERIFICATION_LAYERS = Object.freeze([
  "smoke",
  "contract",
  "regression",
  "feature",
  "heavy",
]);

export const VERIFICATION_CI_PROFILES = Object.freeze([
  "pr-fast",
  "pr-smoke",
  "full",
  "deploy-minimal",
  "perf-pr-gate",
  "scenario-contract-matrix",
]);

const PYTHON_QUICK_COMMAND = "npm run python -- -m unittest tests.test_app_entry_resolver tests.test_main_deferred_detail_promotion_boundary_contract tests.test_scenario_chunk_refresh_contracts tests.test_scenario_renderer_bridge_boundary_contract tests.test_map_renderer_interaction_border_snapshot_orchestration_contract tests.test_perf_gate_contract tests.test_startup_shell -q";

export const VERIFY_CORE_GROUPS = Object.freeze([
  Object.freeze({ id: "infra", title: "Infrastructure contracts" }),
  Object.freeze({ id: "python-quick", title: "Quick Python contracts" }),
  Object.freeze({ id: "startup-node", title: "Startup Node contracts" }),
  Object.freeze({ id: "renderer-owner", title: "Renderer owner contracts" }),
  Object.freeze({ id: "scenario-project-chunk", title: "Scenario, project, and chunk contracts" }),
  Object.freeze({ id: "pages", title: "Pages contract checks" }),
]);

export const VERIFY_CORE_MAIN_THREAD_GROUP = Object.freeze({
  id: "main-thread-e2e",
  title: "Main-thread E2E checks",
});

export const VERIFICATION_DOMAINS = Object.freeze([
  Object.freeze({
    id: "infra:e2e-layer-manifest",
    commandRef: "verify:test:e2e-layers",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/e2e_layering.mjs",
      "tests/e2e/test-layer-manifest.json",
      ".github/workflows/pr-verify.yml",
      ".github/workflows/verify-shared.yml",
    ],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "test-routing",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "infra:verification-selector",
    commandRef: "node tools/select_verification_targets.mjs --check",
    commandType: "direct",
    packageScriptRequired: false,
    sourceRefs: [
      ".gitignore",
      "tools/run_adaptive_tests.mjs",
      "tools/select_verification_targets.mjs",
      "tools/test_route_registry.mjs",
      ".github/workflows/pr-verify.yml",
      ".github/workflows/verify-shared.yml",
    ],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "test-routing",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "infra:sf-ats-contracts",
    commandRef: "verify:supervisor-contracts",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "AGENTS.md",
      "lessons learned.md",
      "docs/testing/sf-ats-overview.md",
      "docs/active/_worktree_registry.md",
      "docs/archive/sf-ats-wp2-supervisor-plan-20260702",
      "tools/ai_test_supervisor",
      "tests/supervisor_domain_registry_behavior.test.mjs",
      "tests/supervisor_schema_contracts.test.mjs",
    ],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "test-routing",
    routeRegistry: true,
    guidance: Object.freeze({
      taskEntry: ["SF-ATS contract and schema health gate"],
      ownerFiles: [
        "AGENTS.md",
        "lessons learned.md",
        "docs/active/_worktree_registry.md",
        "docs/testing/sf-ats-overview.md",
        "tools/ai_test_supervisor",
        "tests/supervisor_domain_registry_behavior.test.mjs",
        "tests/supervisor_schema_contracts.test.mjs",
      ],
      commonChecks: ["npm run verify:supervisor-contracts"],
      riskSignals: [
        "SF-ATS contract drift",
        "supervisor schema drift",
        "domain registry drift",
        "agent verification contract drift",
      ],
      diagnostics: [
        ".runtime/reports/generated/test-adaptive-selection.json",
        ".runtime/reports/generated/test-adaptive-selection.md",
      ],
      status: "active",
    }),
  }),
  Object.freeze({
    id: "infra:core-verification-runner",
    commandRef: "test:node:verify-core-runner",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/run_core_verification.mjs",
      "tests/verify_core_runner_behavior.test.mjs",
      "docs/testing/verify-core.md",
      "package.json",
    ],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    supervisorDomain: "test-routing",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "infra:verification-metadata",
    commandRef: "test:node:verification-metadata",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/verification/verification_domains.mjs",
      "tools/verification/verification_metadata_helpers.mjs",
      "tests/verification_metadata_behavior.test.mjs",
      "docs/testing/verification-metadata.md",
      "package.json",
    ],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "test-routing",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "infra:render-sample-role-policy",
    commandRef: "test:node:render-sample-role-policy",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/perf/render_sample_role_policy.mjs",
      "tools/perf/analyze_render_sample_roles.mjs",
      "tools/perf/run_baseline.mjs",
      "tests/render_sample_role_policy_behavior.test.mjs",
      "tests/perf_role_governed_report_behavior.test.mjs",
      "tests/test_perf_gate_contract.py",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-draw-canvas-orchestration-owner-p2-1-20260710.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/context.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/task.md",
      "package.json",
    ],
    domain: "perf",
    ownerHint: "perf-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "perf",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "infra:test-import-graph",
    commandRef: "verify:test-import-graph",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/build_test_import_graph.mjs",
      "tools/check_test_import_graph.mjs",
      "tests/e2e/test-import-graph.json",
      ".github/workflows/pr-verify.yml",
      ".github/workflows/verify-shared.yml",
    ],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "test-routing",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "infra:architecture-boundaries",
    commandRef: "verify:architecture-boundaries",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/check_architecture_boundaries.mjs",
      "js/core/map_renderer.js",
      "js/core/map_renderer/draw_canvas_orchestration_owner.js",
      "js/core/renderer/cached_pass_compositor_owner.js",
      "js/core/map_renderer/transformed_frame_compositor_owner.js",
      "tests/cached_pass_compositor_owner_behavior.test.mjs",
      "tests/transformed_frame_compositor_owner_behavior.test.mjs",
      "tests/test_map_renderer_frame_compositor_owner_boundary_contract.py",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-cached-pass-compositor-owner-p2-2a-20260711.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-transformed-frame-compositor-owner-p2-2b-20260712.md",
      "js/core/map_renderer/click_selection_transaction_owner.js",
      "tests/click_selection_transaction_owner_behavior.test.mjs",
      "docs/active/renderer-click-selection-pure-decision-owner-p1-8-20260709.md",
      "js/core/renderer/render_pipeline_passes.js",
      "js/core/renderer/viewport_resize_lifecycle_owner.js",
      "js/core/map_renderer/scenario_refresh_runtime.js",
      "js/core/map_renderer/exact_after_settle_scheduler.js",
      "js/core/map_renderer/hgo_runtime_preview_render_owner.js",
      ".github/workflows/pr-verify.yml",
      ".github/workflows/verify-shared.yml",
      "package.json",
    ],
    domain: "architecture-boundaries",
    ownerHint: "architecture",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "architecture-boundaries",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:state-write-allowlist",
    commandRef: "verify:state-write-allowlist",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["tools/check_state_write_allowlist.mjs", "tools/eslint-rules/state-writer-allowlist.json"],
    domain: "architecture-boundaries",
    ownerHint: "architecture",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "architecture-boundaries",
  }),
  Object.freeze({
    id: "verify-core:test-console-allowlist",
    commandRef: "verify:test-console-allowlist",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["tools/check_console_allowlist_decay.mjs", "tests/e2e/support/expectations/console-allowlist.js"],
    domain: "playwright-observability",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "playwright-observability",
  }),
  Object.freeze({
    id: "verify-core:test-timeout-guardrails",
    commandRef: "verify:test-timeout-guardrails",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["tools/check_test_timeout_guardrails.mjs", "tests/e2e/test-layer-manifest.json"],
    domain: "playwright-observability",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "playwright-observability",
  }),
  Object.freeze({
    id: "verify-core:supervisor-plan",
    commandRef: "verify:supervisor-plan",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["tools/ai_test_supervisor/supervise_adaptive_verification.mjs", "tests/supervisor_plan_behavior.test.mjs"],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "test-routing",
  }),
  Object.freeze({
    id: "verify-core:python-quick",
    commandRef: PYTHON_QUICK_COMMAND,
    commandType: "direct",
    packageScriptRequired: false,
    sourceRefs: [
      "tests/test_app_entry_resolver.py",
      "tests/test_main_deferred_detail_promotion_boundary_contract.py",
      "tests/test_scenario_chunk_refresh_contracts.py",
      "tests/test_scenario_renderer_bridge_boundary_contract.py",
      "tests/test_map_renderer_interaction_border_snapshot_orchestration_contract.py",
      "tests/test_perf_gate_contract.py",
      "tests/test_startup_shell.py",
    ],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "python-quick",
    supervisorDomain: "test-routing",
  }),
  ...[
    "test:node:post-ready-scheduler",
    "test:node:main-runtime-diagnostics",
    "test:node:render-runtime-binding",
    "test:node:startup-failure-recovery",
    "test:node:startup-ready-handoff",
    "test:node:deferred-bootstrap",
    "test:node:main-bootstrap-wiring",
  ].map((commandRef) => Object.freeze({
    id: `verify-core:${commandRef}`,
    commandRef,
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["package.json", "tests/verify_core_runner_behavior.test.mjs"],
    domain: "startup",
    ownerHint: "startup-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "startup-node",
    supervisorDomain: "startup",
  })),
  Object.freeze({
    id: "verify-core:test:node:renderer-pass-family-inventory",
    commandRef: "test:node:renderer-pass-family-inventory",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/renderer_pass_family_inventory.mjs",
      "tests/renderer_pass_family_inventory_behavior.test.mjs",
      "js/core/renderer/render_pipeline_catalog.js",
      "js/core/map_renderer/render_pass_catalog.js",
      "js/core/map_renderer.js",
      "js/core/map_renderer/hgo_runtime_preview_render_owner.js",
      "js/core/renderer/transport_overview_render_owner.js",
      "js/core/state/ui_state.js",
      "docs/active/renderer-pass-family-p3-20260713/plan.md",
      "docs/active/renderer-pass-family-p3-20260713/context.md",
      "docs/active/renderer-pass-family-p3-20260713/task.md",
      "docs/active/renderer-pass-family-coupling-matrix-p3-0-20260713.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-runtime-context-foundation",
    commandRef: "test:node:renderer-runtime-context-foundation",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer/renderer_runtime_context.js",
      "tests/renderer_runtime_context_foundation_behavior.test.mjs",
      "docs/active/renderer-runtime-context-foundation-p1-0-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-runtime-context-receiver",
    commandRef: "test:node:renderer-runtime-context-receiver",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "js/core/map_renderer/render_pass_cache_host_owner.js",
      "js/core/map_renderer/render_pass_commit_accounting_owner.js",
      "tests/renderer_runtime_context_receiver_behavior.test.mjs",
      "tests/render_pass_cache_host_owner_inventory.test.mjs",
      "tests/render_pass_commit_accounting_owner_inventory.test.mjs",
      "docs/active/renderer-runtime-context-first-receiver-p1-1-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-runtime-context-render-cache",
    commandRef: "test:node:renderer-runtime-context-render-cache",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "js/core/renderer/render_cache_owner.js",
      "tests/renderer_runtime_context_render_cache_behavior.test.mjs",
      "tests/renderer_runtime_context_receiver_behavior.test.mjs",
      "docs/active/renderer-runtime-context-render-cache-read-model-p1-2-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:python:map-renderer-render-cache-owner-boundary",
    commandRef: "test:python:map-renderer-render-cache-owner-boundary",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/renderer/render_cache_owner.js",
      "tests/test_map_renderer_render_cache_owner_boundary_contract.py",
      "docs/active/renderer-runtime-context-render-cache-read-model-p1-2-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-runtime-context-projection-viewport",
    commandRef: "test:node:renderer-runtime-context-projection-viewport",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer/renderer_runtime_context.js",
      "tests/renderer_runtime_context_projection_viewport_behavior.test.mjs",
      "docs/active/renderer-runtime-context-projection-viewport-p1-3-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:python:map-renderer-projection-viewport-context-boundary",
    commandRef: "test:python:map-renderer-projection-viewport-context-boundary",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "js/core/renderer/renderer_projection_path_owner.js",
      "js/core/renderer/viewport_read_model_owner.js",
      "js/core/renderer/viewport_command_owner.js",
      "tests/test_map_renderer_projection_viewport_context_boundary_contract.py",
      "tests/renderer_runtime_context_receiver_behavior.test.mjs",
      "docs/active/renderer-runtime-context-projection-viewport-p1-3-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-runtime-context-viewport-mutation",
    commandRef: "test:node:renderer-runtime-context-viewport-mutation",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "js/core/renderer/renderer_fit_projection_owner.js",
      "js/core/renderer/renderer_viewport_update_owner.js",
      "js/core/renderer/viewport_resize_lifecycle_owner.js",
      "tests/renderer_runtime_context_viewport_mutation_behavior.test.mjs",
      "docs/active/renderer-runtime-context-viewport-mutation-chain-p1-4-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:python:map-renderer-viewport-mutation-context-boundary",
    commandRef: "test:python:map-renderer-viewport-mutation-context-boundary",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "js/core/map_renderer/public.js",
      "tools/eslint-rules/state-writer-allowlist.json",
      "tests/test_map_renderer_viewport_mutation_context_boundary_contract.py",
      "docs/active/renderer-runtime-context-viewport-mutation-chain-p1-4-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-viewport-update-owner",
    commandRef: "test:node:renderer-viewport-update-owner",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/renderer/renderer_viewport_update_owner.js",
      "tests/renderer_viewport_update_owner_behavior.test.mjs",
      "docs/active/renderer-runtime-context-viewport-mutation-chain-p1-4-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:viewport-resize-lifecycle-owner",
    commandRef: "test:node:viewport-resize-lifecycle-owner",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/renderer/viewport_resize_lifecycle_owner.js",
      "tests/viewport_resize_lifecycle_owner_behavior.test.mjs",
      "docs/active/renderer-runtime-context-viewport-mutation-chain-p1-4-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-runtime-context-interaction",
    commandRef: "test:node:renderer-runtime-context-interaction",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "js/core/renderer/zoom_interaction_lifecycle_owner.js",
      "js/core/renderer/map_interaction_event_binding_owner.js",
      "tests/renderer_runtime_context_interaction_behavior.test.mjs",
      "tests/renderer_runtime_context_receiver_behavior.test.mjs",
      "tests/zoom_interaction_lifecycle_owner_behavior.test.mjs",
      "tests/map_interaction_event_binding_owner_behavior.test.mjs",
      "docs/active/renderer-runtime-context-interaction-p1-5-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:python:map-renderer-interaction-context-boundary",
    commandRef: "test:python:map-renderer-interaction-context-boundary",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "js/core/renderer/zoom_interaction_lifecycle_owner.js",
      "js/core/renderer/map_interaction_event_binding_owner.js",
      "js/core/map_renderer/public.js",
      "tools/eslint-rules/state-writer-allowlist.json",
      "tests/test_map_renderer_interaction_context_boundary_contract.py",
      "docs/active/renderer-runtime-context-interaction-p1-5-20260709.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-runtime-context-hit-hover",
    commandRef: "test:node:renderer-runtime-context-hit-hover",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "js/core/map_renderer/hit_canvas_scheduling_owner.js",
      "js/core/map_renderer/map_hover_interaction_owner.js",
      "tests/renderer_runtime_context_hit_hover_behavior.test.mjs",
      "tests/renderer_runtime_context_interaction_behavior.test.mjs",
      "tests/hit_canvas_scheduling_owner_behavior.test.mjs",
      "tests/hit_canvas_scheduling_owner_inventory.test.mjs",
      "tests/map_hover_interaction_owner_behavior.test.mjs",
      "tests/map_hover_interaction_owner_inventory.test.mjs",
      "docs/active/renderer-runtime-context-hit-hover-p1-6-20260709.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/plan.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/context.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/task.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:python:map-renderer-hit-hover-context-boundary",
    commandRef: "test:python:map-renderer-hit-hover-context-boundary",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "js/core/map_renderer/hit_canvas_scheduling_owner.js",
      "js/core/map_renderer/map_hover_interaction_owner.js",
      "js/core/map_renderer/public.js",
      "tools/eslint-rules/state-writer-allowlist.json",
      "tests/test_map_renderer_hit_hover_context_boundary_contract.py",
      "docs/active/renderer-runtime-context-hit-hover-p1-6-20260709.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/plan.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/context.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/task.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:click-selection-transaction-owner",
    commandRef: "test:node:click-selection-transaction-owner",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/click_selection_transaction_owner.js",
      "tests/click_selection_transaction_owner_behavior.test.mjs",
      "tests/renderer_click_selection_transaction_inventory_boundary.test.mjs",
      "tests/test_map_renderer_click_selection_transaction_boundary_contract.py",
      "tools/check_architecture_boundaries.mjs",
      "tools/verification/verification_domains.mjs",
      "tests/verification_metadata_behavior.test.mjs",
      "docs/active/renderer-click-selection-transaction-preflight-20260702.md",
      "docs/active/renderer-click-selection-transaction-preflight-p1-7-20260709.md",
      "docs/active/renderer-click-selection-pure-decision-owner-p1-8-20260709.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/plan.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/context.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/task.md",
      "docs/active/_worktree_registry.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-click-selection-transaction-inventory",
    commandRef: "test:node:renderer-click-selection-transaction-inventory",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/click_selection_transaction_owner.js",
      "js/core/map_renderer/map_hover_interaction_owner.js",
      "js/core/renderer/map_interaction_event_binding_owner.js",
      "js/core/map_renderer/interaction_hit_candidates.js",
      "js/core/interaction_funnel.js",
      "js/core/history_manager.js",
      "js/core/dirty_state.js",
      "js/core/map_renderer/public.js",
      "tools/eslint-rules/state-writer-allowlist.json",
      "tests/renderer_click_selection_transaction_inventory_boundary.test.mjs",
      "tests/click_selection_transaction_owner_behavior.test.mjs",
      "tests/test_map_renderer_click_selection_transaction_boundary_contract.py",
      "tools/check_architecture_boundaries.mjs",
      "tools/verification/verification_domains.mjs",
      "tests/verification_metadata_behavior.test.mjs",
      "docs/active/renderer-click-selection-transaction-preflight-20260702.md",
      "docs/active/renderer-click-selection-transaction-preflight-p1-7-20260709.md",
      "docs/active/renderer-click-selection-pure-decision-owner-p1-8-20260709.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/plan.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/context.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/task.md",
      "docs/active/_worktree_registry.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:renderer-draw-canvas-orchestration-inventory",
    commandRef: "test:node:renderer-draw-canvas-orchestration-inventory",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/draw_canvas_orchestration_owner.js",
      "js/core/renderer/cached_pass_compositor_owner.js",
      "js/core/map_renderer/transformed_frame_compositor_owner.js",
      "tests/draw_canvas_orchestration_owner_behavior.test.mjs",
      "tests/cached_pass_compositor_owner_behavior.test.mjs",
      "tests/transformed_frame_compositor_owner_behavior.test.mjs",
      "tests/test_map_renderer_draw_canvas_orchestration_owner_boundary_contract.py",
      "tests/test_map_renderer_frame_compositor_owner_boundary_contract.py",
      "tests/renderer_draw_canvas_orchestration_inventory_boundary.test.mjs",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-draw-canvas-orchestration-preflight-20260702.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-draw-canvas-orchestration-owner-p2-1-20260710.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-cached-pass-compositor-owner-p2-2a-20260711.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-transformed-frame-compositor-owner-p2-2b-20260712.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/plan.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/context.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/task.md",
      "tools/check_architecture_boundaries.mjs",
      "tools/verification/verification_domains.mjs",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:draw-canvas-orchestration-owner",
    commandRef: "test:node:draw-canvas-orchestration-owner",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/draw_canvas_orchestration_owner.js",
      "tests/draw_canvas_orchestration_owner_behavior.test.mjs",
      "tests/renderer_draw_canvas_orchestration_inventory_boundary.test.mjs",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-draw-canvas-orchestration-owner-p2-1-20260710.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:python:map-renderer-draw-canvas-orchestration-boundary",
    commandRef: "test:python:map-renderer-draw-canvas-orchestration-boundary",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/draw_canvas_orchestration_owner.js",
      "js/core/map_renderer/public.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "tools/eslint-rules/state-writer-allowlist.json",
      "tools/check_architecture_boundaries.mjs",
      "tests/draw_canvas_orchestration_owner_behavior.test.mjs",
      "tests/test_map_renderer_draw_canvas_orchestration_owner_boundary_contract.py",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-draw-canvas-orchestration-owner-p2-1-20260710.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "infra:williams-crossover-governance",
    commandRef: "test:node:williams-crossover-governance",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/perf/williams_crossover_policy.mjs",
      "tools/perf/run_williams_crossover.mjs",
      "tools/perf/williams_crossover_windows_runtime.mjs",
      "tools/perf/williams_crossover_windows_job_runner.cs",
      "tools/perf/williams_crossover_power_scheme.ps1",
      "tools/perf/run_baseline.mjs",
      "tools/perf/render_sample_role_policy.mjs",
      "tests/williams_crossover_governance_behavior.test.mjs",
      "docs/archive/renderer-frame-orchestration-p2-20260710/plan.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/context.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/task.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/rerun07-final-repeat-governance.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/rerun08-harness-recovery-governance.md",
      "docs/active/_worktree_registry.md",
      "package.json",
    ],
    domain: "perf",
    ownerHint: "perf-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "perf",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "infra:williams-crossover-job-runner",
    commandRef: "test:node:williams-crossover-job-runner",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/perf/williams_crossover_windows_runtime.mjs",
      "tools/perf/williams_crossover_windows_job_runner.cs",
      "tools/perf/run_williams_crossover.mjs",
      "tools/perf/williams_crossover_policy.mjs",
      "tests/williams_crossover_windows_job_runner_behavior.test.mjs",
      "tests/williams_crossover_windows_job_runner_integration.test.mjs",
      "tests/williams_crossover_governance_behavior.test.mjs",
      "docs/archive/renderer-frame-orchestration-p2-20260710/plan.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/context.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/task.md",
      "docs/active/_worktree_registry.md",
      "package.json",
    ],
    domain: "perf",
    ownerHint: "perf-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "infra",
    supervisorDomain: "perf",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "perf:williams-crossover-live",
    commandRef: "perf:williams-crossover:run",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/perf/williams_crossover_policy.mjs",
      "tools/perf/run_williams_crossover.mjs",
      "tools/perf/williams_crossover_windows_runtime.mjs",
      "tools/perf/williams_crossover_windows_job_runner.cs",
      "tools/perf/williams_crossover_power_scheme.ps1",
      "tools/perf/run_baseline.mjs",
      "tools/perf/render_sample_role_policy.mjs",
      "package-lock.json",
      "package.json",
    ],
    domain: "perf",
    ownerHint: "perf-runtime",
    layer: "heavy",
    cost: "heavy",
    resourceLocks: ["perf-dev-server", "browser-dev-server", "playwright-browser", ".runtime-output", "system-power-scheme"],
    executionOwner: "main-thread",
    ciProfile: "perf-pr-gate",
    supervisorDomain: "perf",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "perf:williams-power-scheme-live-preflight",
    commandRef: "perf:williams-power-scheme:live-preflight",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/perf/williams_crossover_power_scheme.ps1",
      "tools/perf/run_williams_crossover.mjs",
      "tools/perf/williams_crossover_policy.mjs",
      "tests/williams_crossover_governance_behavior.test.mjs",
      "package.json",
    ],
    domain: "perf",
    ownerHint: "perf-runtime",
    layer: "smoke",
    cost: "contract",
    resourceLocks: ["system-power-scheme"],
    executionOwner: "main-thread",
    ciProfile: "perf-pr-gate",
    supervisorDomain: "perf",
    routeRegistry: true,
    optionalMainThread: true,
  }),
  Object.freeze({
    id: "perf:williams-crossover-telemetry-live",
    commandRef: "test:node:williams-crossover-telemetry-live",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/perf/williams_crossover_policy.mjs",
      "tools/perf/williams_crossover_windows_runtime.mjs",
      "tests/williams_crossover_windows_job_runner_integration.test.mjs",
      "package.json",
    ],
    domain: "perf",
    ownerHint: "perf-runtime",
    layer: "regression",
    cost: "contract",
    resourceLocks: ["perf-dev-server"],
    executionOwner: "main-thread",
    ciProfile: "perf-pr-gate",
    supervisorDomain: "perf",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:city-points-render-owner",
    commandRef: "test:node:city-points-render-owner",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/renderer/city_points_render_owner.js",
      "js/core/renderer/urban_city_policy.js",
      "tests/city_points_render_owner_behavior.test.mjs",
      "tests/urban_city_policy_strategic_values_behavior.test.mjs",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "regression",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:python:map-renderer-city-points-boundary",
    commandRef: "test:python:map-renderer-city-points-boundary",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/renderer/city_points_render_owner.js",
      "js/core/renderer/urban_city_policy.js",
      "tests/test_map_renderer_urban_city_policy_boundary_contract.py",
      "tests/test_map_renderer_city_label_owner_boundary_contract.py",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:cached-pass-compositor-owner",
    commandRef: "test:node:cached-pass-compositor-owner",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/renderer/cached_pass_compositor_owner.js",
      "tests/cached_pass_compositor_owner_behavior.test.mjs",
      "tests/renderer_draw_canvas_orchestration_inventory_boundary.test.mjs",
      "tests/scenario_chunk_contracts.test.mjs",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-cached-pass-compositor-owner-p2-2a-20260711.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:node:transformed-frame-compositor-owner",
    commandRef: "test:node:transformed-frame-compositor-owner",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/transformed_frame_compositor_owner.js",
      "tests/transformed_frame_compositor_owner_behavior.test.mjs",
      "tests/renderer_draw_canvas_orchestration_inventory_boundary.test.mjs",
      "tests/scenario_chunk_contracts.test.mjs",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-transformed-frame-compositor-owner-p2-2b-20260712.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "renderer:transformed-frame-compositor-runtime",
    commandRef: "test:e2e:dev:scenario-chunk-runtime",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/transformed_frame_compositor_owner.js",
      "tests/e2e/dev/scenario_chunk_exact_after_settle_regression.dev.spec.js",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "regression",
    cost: "heavy",
    resourceLocks: ["browser-dev-server", "playwright-browser", ".runtime-output"],
    executionOwner: "main-thread",
    ciProfile: "pr-smoke",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
    optionalMainThread: true,
  }),
  Object.freeze({
    id: "verify-core:test:python:map-renderer-frame-compositor-boundary",
    commandRef: "test:python:map-renderer-frame-compositor-boundary",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/renderer/cached_pass_compositor_owner.js",
      "js/core/map_renderer/transformed_frame_compositor_owner.js",
      "js/core/map_renderer/public.js",
      "js/core/map_renderer/renderer_runtime_context.js",
      "tools/eslint-rules/state-writer-allowlist.json",
      "tools/check_architecture_boundaries.mjs",
      "tests/cached_pass_compositor_owner_behavior.test.mjs",
      "tests/transformed_frame_compositor_owner_behavior.test.mjs",
      "tests/test_map_renderer_frame_compositor_owner_boundary_contract.py",
      "tests/test_pages_dist_startup_shell.py",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-cached-pass-compositor-owner-p2-2a-20260711.md",
      "docs/archive/renderer-frame-orchestration-p2-20260710/renderer-transformed-frame-compositor-owner-p2-2b-20260712.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:test:python:map-renderer-click-selection-transaction-boundary",
    commandRef: "test:python:map-renderer-click-selection-transaction-boundary",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "js/core/map_renderer.js",
      "js/core/map_renderer/click_selection_transaction_owner.js",
      "js/core/map_renderer/map_hover_interaction_owner.js",
      "js/core/renderer/map_interaction_event_binding_owner.js",
      "js/core/map_renderer/interaction_hit_candidates.js",
      "js/core/interaction_funnel.js",
      "js/core/history_manager.js",
      "js/core/dirty_state.js",
      "js/core/map_renderer/public.js",
      "tools/eslint-rules/state-writer-allowlist.json",
      "tests/test_map_renderer_click_selection_transaction_boundary_contract.py",
      "tests/click_selection_transaction_owner_behavior.test.mjs",
      "tests/renderer_click_selection_transaction_inventory_boundary.test.mjs",
      "tools/check_architecture_boundaries.mjs",
      "tools/verification/verification_domains.mjs",
      "tests/verification_metadata_behavior.test.mjs",
      "docs/active/renderer-click-selection-transaction-preflight-20260702.md",
      "docs/active/renderer-click-selection-transaction-preflight-p1-7-20260709.md",
      "docs/active/renderer-click-selection-pure-decision-owner-p1-8-20260709.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/plan.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/context.md",
      "docs/active/renderer-runtime-context-p1-remaining-20260709/task.md",
      "docs/active/_worktree_registry.md",
      "package.json",
    ],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
    routeRegistry: true,
  }),
  ...[
    "test:node:render-pass-catalog",
    "test:node:render-pipeline-catalog",
    "test:node:renderer-render-request-boundary",
    "test:node:renderer-render-phase-lifecycle",
    "test:node:renderer-hit-canvas-scheduling-inventory",
    "test:node:render-pass-cache-host-owner-suite",
    "test:node:render-pass-commit-accounting-owner-suite",
    "test:node:hit-canvas-scheduling-owner-suite",
    "test:node:zoom-interaction-lifecycle-owner",
    "test:node:map-interaction-event-binding-owner",
    "test:node:visible-frame-diagnostics",
    "test:node:render-cache-owner",
    "test:node:render-transform-reuse-policy-owner",
    "test:node:viewport-read-model-owner",
    "test:node:viewport-command-owner",
  ].map((commandRef) => Object.freeze({
    id: `verify-core:${commandRef}`,
    commandRef,
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["package.json", "tests/verify_core_runner_behavior.test.mjs"],
    domain: "renderer-runtime",
    ownerHint: "renderer-runtime",
    layer: "contract",
    cost: "fast",
    resourceLocks: [],
    executionOwner: "child-safe",
    ciProfile: "pr-fast",
    verifyCoreDefaultGroup: "renderer-owner",
    supervisorDomain: "renderer-runtime",
  })),
  ...[
    "verify:scenario-contracts:strict",
    "test:node:scenario-chunk-contracts",
    "test:node:scenario-apply-transaction-ownership",
    "test:node:scenario-lifecycle-runtime-behavior",
    "test:node:scenario-runtime-state-behavior",
    "test:node:annotation-productization",
  ].map((commandRef) => Object.freeze({
    id: `verify-core:${commandRef}`,
    commandRef,
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["package.json", "tests/verify_core_runner_behavior.test.mjs"],
    domain: "scenario-runtime",
    ownerHint: "scenario-runtime",
    layer: "contract",
    cost: "contract",
    resourceLocks: commandRef === "verify:scenario-contracts:strict" ? ["scenario-data", ".runtime-output"] : [],
    executionOwner: commandRef === "verify:scenario-contracts:strict" ? "main-thread" : "child-safe",
    ciProfile: commandRef === "verify:scenario-contracts:strict" ? "scenario-contract-matrix" : "pr-fast",
    verifyCoreDefaultGroup: "scenario-project-chunk",
    supervisorDomain: "scenario-runtime",
  })),
  Object.freeze({
    id: "infra:pages-dist",
    commandRef: "verify:pages-dist",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: [
      "tools/build_pages_dist.py",
      "tests/test_pages_dist_startup_shell.py",
      "js/core/map_renderer.js",
      "js/core/map_renderer",
      "js/core/renderer/cached_pass_compositor_owner.js",
      ".github/workflows/verify-shared.yml",
    ],
    domain: "pages-dist",
    ownerHint: "deploy-runtime",
    layer: "heavy",
    cost: "heavy",
    resourceLocks: ["dist", ".runtime-output"],
    executionOwner: "main-thread",
    ciProfile: "deploy-minimal",
    verifyCoreDefaultGroup: "pages",
    supervisorDomain: "pages-dist",
    routeRegistry: true,
  }),
  Object.freeze({
    id: "verify-core:dist-drift",
    commandRef: "verify:dist-drift",
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["tools/build_pages_dist.py", "dist/pages-dist-manifest.json", "dist/app"],
    domain: "pages-dist",
    ownerHint: "deploy-runtime",
    layer: "heavy",
    cost: "heavy",
    resourceLocks: ["dist", ".runtime-output"],
    executionOwner: "main-thread",
    ciProfile: "deploy-minimal",
    verifyCoreDefaultGroup: "pages",
    supervisorDomain: "pages-dist",
  }),
  ...[
    "test:e2e:smoke",
    "test:e2e:scenario-apply-concurrency",
    "test:e2e:project-save-load",
    "test:e2e:interaction-funnel",
  ].map((commandRef) => Object.freeze({
    id: `verify-core-main-thread:${commandRef}`,
    commandRef,
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["package.json", "tests/e2e"],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "smoke",
    cost: "heavy",
    resourceLocks: ["browser-dev-server", "playwright-browser", ".runtime-output"],
    executionOwner: "main-thread",
    ciProfile: "full",
    verifyCoreMainThread: true,
    supervisorDomain: "test-routing",
  })),
  ...[
    "test:e2e:tno-contracts",
    "test:e2e:water-rendering",
    "test:e2e:city-rendering",
  ].map((commandRef) => Object.freeze({
    id: `verify-core-optional:${commandRef}`,
    commandRef,
    commandType: "package-script",
    packageScriptRequired: true,
    sourceRefs: ["package.json", "tests/e2e"],
    domain: "test-routing",
    ownerHint: "test-infra",
    layer: "regression",
    cost: "heavy",
    resourceLocks: ["browser-dev-server", "playwright-browser", ".runtime-output"],
    executionOwner: "main-thread",
    ciProfile: "full",
    optionalMainThread: true,
    supervisorDomain: "test-routing",
  })),
]);
