EUROPE_GEO_SEEDS = {
    "Andalusia": "安达卢西亚",
    "Aragon": "阿拉贡",
    "Bavaria": "巴伐利亚",
    "Basque Country": "巴斯克",
    "Baden-Württemberg": "巴登-符腾堡",
    "Berlin": "柏林",
    "Brandenburg": "勃兰登堡",
    "Bremen": "不来梅",
    "Brittany": "布列塔尼",
    "Brussels": "布鲁塞尔",
    "Campania": "坎帕尼亚",
    "Catalonia": "加泰罗尼亚",
    "Castile and Leon": "卡斯蒂利亚-莱昂",
    "Castile-La Mancha": "卡斯蒂利亚-拉曼恰",
    "Corsica": "科西嘉",
    "Dublin": "都柏林",
    "Emilia-Romagna": "艾米利亚-罗马涅",
    "England": "英格兰",
    "Flanders": "佛兰德",
    "Friesland": "弗里斯兰",
    "Galicia": "加利西亚",
    "Greater Poland": "大波兰",
    "Hamburg": "汉堡",
    "Hesse": "黑森",
    "Ile-de-France": "法兰西岛",
    "Lazio": "拉齐奥",
    "Lesser Poland": "小波兰",
    "Liguria": "利古里亚",
    "Lombardy": "伦巴第",
    "Lower Saxony": "下萨克森",
    "Luxembourg": "卢森堡",
    "Madrid": "马德里",
    "Masovia": "马佐夫舍",
    "Mecklenburg-Vorpommern": "梅克伦堡-前波美拉尼亚",
    "Munster": "明斯特",
    "Naples": "那不勒斯",
    "Normandy": "诺曼底",
    "Northern Ireland": "北爱尔兰",
    "North Holland": "北荷兰",
    "North Rhine-Westphalia": "北莱茵-威斯特法伦",
    "Occitanie": "奥克西塔尼",
    "Piedmont": "皮埃蒙特",
    "Provence-Alpes-Cote d'Azur": "普罗旺斯-阿尔卑斯-蔚蓝海岸",
    "Sardinia": "撒丁岛",
    "Saxony": "萨克森",
    "Scotland": "苏格兰",
    "Sicily": "西西里",
    "Silesia": "西里西亚",
    "South Holland": "南荷兰",
    "Stockholm": "斯德哥尔摩",
    "Tuscany": "托斯卡纳",
    "Thuringia": "图林根",
    "Utrecht": "乌得勒支",
    "Valencia": "瓦伦西亚",
    "Veneto": "威尼托",
    "Wallonia": "瓦隆",
    "Wales": "威尔士",
}
