export const RENDER_PASS_FAMILY_IDS = Object.freeze([
  "foundation",
  "political",
  "hgo-preview",
  "context",
  "visual-effects",
  "borders",
  "labels",
]);

export const RENDER_PASS_IMPLEMENTATION_STATUS_IDS = Object.freeze([
  "inline",
  "thin-wrapper",
  "delegated-existing",
  "owned-p3",
  "hold",
]);

export const RENDER_PASS_PLANNED_PHASE_IDS = Object.freeze([
  "P3.1",
  "P3.2",
  "P3.3a",
  "existing-delegated",
  "hold",
  "future-review",
]);

export const RENDER_PASS_RISK_TIER_IDS = Object.freeze(["low", "medium", "high"]);

export const RENDER_PASS_STATE_READ_CLASS_IDS = Object.freeze([
  "viewport",
  "appearance",
  "scenario",
  "map-data",
  "interaction",
  "render-cache",
  "clock",
  "diagnostics",
]);

export const RENDER_PASS_STATE_WRITE_CLASS_IDS = Object.freeze([
  "pass-surface",
  "owner-cache",
  "runtime-state",
  "diagnostics",
]);

export const RENDER_PASS_SURFACE_IDS = Object.freeze(["canvas", "svg", "hybrid"]);
export const RENDER_PASS_PERF_SENSITIVITY_IDS = Object.freeze(["low", "medium", "high"]);

const freezeRecord = (record) => Object.freeze({
  ...record,
  stateReadClass: Object.freeze(record.stateReadClass),
  stateWriteClass: Object.freeze(record.stateWriteClass),
  existingDependencyOwners: Object.freeze(record.existingDependencyOwners),
  browserLanes: Object.freeze(record.browserLanes),
});

export const RENDER_PASS_FAMILY_INVENTORY = Object.freeze([
  freezeRecord({
    passName: "background",
    familyId: "foundation",
    entryFunction: "drawBackgroundPass",
    implementationStatus: "inline",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "hold",
    riskTier: "high",
    stateReadClass: ["viewport", "appearance", "scenario", "map-data", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [
      "js/core/renderer/ocean_render_owner.js",
      "js/core/renderer/asset_url_policy.js",
      "js/core/renderer/intensity_field_mask_owner.js",
    ],
    browserLanes: ["test:e2e:water-rendering"],
    perfSensitivity: "high",
    notes: "foundational scenario-aware ocean and bathymetry ownership held for later review",
  }),
  freezeRecord({
    passName: "physicalBase",
    familyId: "foundation",
    entryFunction: "drawPhysicalBasePass",
    implementationStatus: "delegated-existing",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "existing-delegated",
    riskTier: "medium",
    stateReadClass: ["viewport", "appearance", "scenario", "map-data", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: ["js/core/renderer/physical_layer_render_owner.js"],
    browserLanes: ["test:e2e:physical-layer-runtime-contract"],
    perfSensitivity: "high",
    notes: "existing physical owner remains authoritative",
  }),
  freezeRecord({
    passName: "political",
    familyId: "political",
    entryFunction: "drawPoliticalPass",
    implementationStatus: "inline",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "P3.3a",
    riskTier: "high",
    stateReadClass: ["viewport", "appearance", "scenario", "map-data", "interaction", "render-cache", "diagnostics"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [
      "js/core/political_raster_worker_client.js",
      "js/core/map_renderer/political_raster_worker_packet.js",
      "js/core/map_renderer/render_request_boundary_owner.js",
      "js/core/renderer/color_resolution_strategy.js",
      "js/core/renderer/political_collection_owner.js",
      "js/core/renderer/spatial_index_runtime_owner.js",
      "js/core/renderer/visible_frame_diagnostics_owner.js",
    ],
    browserLanes: ["test:e2e:scenario-resilience", "test:e2e:water-rendering", "test:e2e:tno-contracts"],
    perfSensitivity: "high",
    notes: "P3.3a preflight scope only; worker client, packet builder, and accepted-result render request remain inline dependencies",
  }),
  freezeRecord({
    passName: "hgoPreview",
    familyId: "hgo-preview",
    entryFunction: "drawHgoPreviewPass",
    implementationStatus: "delegated-existing",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "existing-delegated",
    riskTier: "medium",
    stateReadClass: ["viewport", "scenario", "map-data", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [
      "js/core/map_renderer/hgo_runtime_preview_render_owner.js",
      "js/core/map_renderer/hgo_runtime_preview_frame_commit.js",
    ],
    browserLanes: [],
    perfSensitivity: "high",
    notes: "dedicated browser lane gap; static and contract evidence only",
  }),
  freezeRecord({
    passName: "contextBase",
    familyId: "context",
    entryFunction: "drawContextBasePass",
    implementationStatus: "inline",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "P3.2",
    riskTier: "high",
    stateReadClass: ["viewport", "appearance", "scenario", "map-data", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [
      "js/core/renderer/physical_layer_render_owner.js",
      "js/core/renderer/river_layer_render_owner.js",
      "js/core/renderer/color_resolution_strategy.js",
    ],
    browserLanes: ["test:e2e:physical-layer-runtime-contract", "test:e2e:water-rendering"],
    perfSensitivity: "high",
    notes: "P3.2 context-base extraction candidate",
  }),
  freezeRecord({
    passName: "contextScenario",
    familyId: "context",
    entryFunction: "drawContextScenarioPass",
    implementationStatus: "inline",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "P3.2",
    riskTier: "high",
    stateReadClass: ["viewport", "appearance", "scenario", "map-data", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [
      "js/core/renderer/scenario_water_cache_policy_owner.js",
      "js/core/renderer/scenario_relief_overlay_render_owner.js",
      "js/core/renderer/color_resolution_strategy.js",
    ],
    browserLanes: ["test:e2e:scenario-resilience", "test:e2e:water-rendering", "test:e2e:tno-contracts"],
    perfSensitivity: "high",
    notes: "P3.2 scenario overlay extraction candidate",
  }),
  freezeRecord({
    passName: "effects",
    familyId: "visual-effects",
    entryFunction: "drawEffectsPass",
    implementationStatus: "inline",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "P3.1",
    riskTier: "medium",
    stateReadClass: ["viewport", "appearance", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: ["js/core/map_renderer/render_request_boundary_owner.js"],
    browserLanes: ["test:e2e:layer:regression"],
    perfSensitivity: "high",
    notes: "P3.1 full-sphere paper effect with async texture rerender boundary",
  }),
  freezeRecord({
    passName: "lineEffects",
    familyId: "visual-effects",
    entryFunction: "drawLineEffectsPass",
    implementationStatus: "inline",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "P3.1",
    riskTier: "medium",
    stateReadClass: ["viewport", "appearance", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [],
    browserLanes: ["test:e2e:layer:regression"],
    perfSensitivity: "medium",
    notes: "P3.1 graticule and draft-grid lines with shared style config normalization",
  }),
  freezeRecord({
    passName: "dayNight",
    familyId: "visual-effects",
    entryFunction: "drawDayNightPass",
    implementationStatus: "inline",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "P3.1",
    riskTier: "medium",
    stateReadClass: ["viewport", "appearance", "scenario", "map-data", "interaction", "render-cache", "clock"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [
      "js/core/renderer/city_lights_render_owner.js",
      "js/core/renderer/urban_city_policy.js",
    ],
    browserLanes: ["test:e2e:city-rendering"],
    perfSensitivity: "high",
    notes: "P3.1 scenario- and clock-coupled shadow and city lights with urban policy and shared style config normalization",
  }),
  freezeRecord({
    passName: "borders",
    familyId: "borders",
    entryFunction: "drawBordersPass",
    implementationStatus: "thin-wrapper",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "hold",
    riskTier: "high",
    stateReadClass: ["viewport", "appearance", "scenario", "map-data", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [
      "js/core/renderer/border_draw_owner.js",
      "js/core/renderer/ocean_render_owner.js",
    ],
    browserLanes: ["test:e2e:layer:regression", "test:e2e:tno-contracts"],
    perfSensitivity: "high",
    notes: "HGO and data guards remain in the wrapper; border draw reaches ocean coastal accents through its injected helper",
  }),
  freezeRecord({
    passName: "contextMarkers",
    familyId: "context",
    entryFunction: "drawContextMarkersPass",
    implementationStatus: "inline",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "P3.2",
    riskTier: "high",
    stateReadClass: ["viewport", "appearance", "scenario", "map-data", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [
      "js/core/renderer/transport_overview_render_owner.js",
      "js/core/renderer/strategic_resource_markers.js",
      "js/core/renderer/city_points_render_owner.js",
      "js/core/renderer/urban_city_policy.js",
      "js/core/renderer/color_resolution_strategy.js",
    ],
    browserLanes: ["test:e2e:city-rendering", "test:e2e:scenario-resilience", "test:e2e:tno-contracts"],
    perfSensitivity: "high",
    notes: "P3.2 transport, strategic and city marker orchestration with shared transport style normalization",
  }),
  freezeRecord({
    passName: "textureLabels",
    familyId: "visual-effects",
    entryFunction: "drawTextureLabelEffectsPass",
    implementationStatus: "inline",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "P3.1",
    riskTier: "medium",
    stateReadClass: ["viewport", "appearance", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "runtime-state", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [],
    browserLanes: ["test:e2e:layer:regression"],
    perfSensitivity: "low",
    notes: "P3.1 graticule label effect with shared style config normalization",
  }),
  freezeRecord({
    passName: "labels",
    familyId: "labels",
    entryFunction: "drawLabelsPass",
    implementationStatus: "thin-wrapper",
    entryHostPath: "js/core/map_renderer.js",
    plannedPhase: "future-review",
    riskTier: "medium",
    stateReadClass: ["viewport", "appearance", "scenario", "map-data", "interaction", "render-cache"],
    stateWriteClass: ["pass-surface", "owner-cache", "diagnostics"],
    canvasOrSvg: "canvas",
    existingDependencyOwners: [
      "js/core/renderer/city_points_render_owner.js",
      "js/core/renderer/city_label_owner.js",
      "js/core/renderer/urban_city_policy.js",
      "js/core/renderer/color_resolution_strategy.js",
    ],
    browserLanes: ["test:e2e:city-rendering"],
    perfSensitivity: "medium",
    notes: "blank labels stay inline; city reveal, city label, and color resolution delegate; future review",
  }),
]);
